local mediaPath = "Interface\\media\\"

-- Small tweaks and register hider/shower
local addon = CreateFrame("Frame", nil, UIParent)
addon:RegisterEvent("PLAYER_ENTERING_WORLD")
addon:SetScript("OnEvent", function(self, event, unit, ...)
    addon:UnregisterEvent("PLAYER_ENTERING_WORLD")
    -- LootHistoryFrame:SetScale(1.5)
    -- TimeManagerClockButton:Hide()
    MicroMenu:Hide()
    BagsBar:Hide()
    MainStatusTrackingBarContainer:Hide()
    ChatFrame1:SetFont(mediaPath.."Asap-Bold.ttf", 15, "OUTLINE")
    ChatFrame2:SetFont(mediaPath.."Asap-Bold.ttf", 15, "OUTLINE")
    ChatFrame3:SetFont(mediaPath.."Asap-Bold.ttf", 15, "OUTLINE")
    ChatFrame4:SetFont(mediaPath.."Asap-Bold.ttf", 15, "OUTLINE")
    ChatFrame1:ClearAllPoints()
    ChatFrame1:SetWidth(615)
    ChatFrame1:SetHeight(250)
    ChatFrame1:SetClampRectInsets(0, 0, 0, 0)
    ChatFrame1:SetPoint("BOTTOMLEFT", UIParent, "BOTTOMLEFT", 12, 12)
    ChatFrame4:ClearAllPoints()
    ChatFrame4:SetWidth(615)
    ChatFrame4:SetHeight(250)
    ChatFrame4:SetClampRectInsets(0, 0, 0, 0)
    ChatFrame4:SetPoint("BOTTOMRIGHT", UIParent, "BOTTOMRIGHT", -12, 12)
end)